import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const DRY_RUN = process.argv.includes('--dry-run') || process.env.DRY_RUN === 'true';

const SEED_RULES = [
  // ─── EXTERIOR / MEASUREMENT ───
  {
    ruleKey: 'ww-brick-outside-measure',
    name: 'Brick → Outside Measure / EXT Install',
    description: 'Brick exterior requires outside measurement basis and EXT install type by default.',
    category: 'exterior_install',
    triggerField: 'exteriorType',
    operator: 'equals',
    triggerValue: 'Brick',
    actionType: 'set_field',
    actionField: 'installType',
    actionValue: 'EXT',
    severity: 'warning',
    priority: 10,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Labor Requirement Memos (Trim)',
    sourcePage: '102',
    fieldRepGuidance: 'Brick is measured brick-to-brick. Measurement method must be outside.',
    installerNoteTemplate: 'Brick install - outside measure used.',
    orderFormImpact: 'Labor section - Install type to EXT',
    contractImpact: 'Install type - EXT',
    pricingImpact: 'Included in base installation',
    workbookMappingKey: 'Order Form Labor Section',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-siding-header-flashing',
    name: 'Siding → Header Flashing Suggested',
    description: 'Siding exterior suggests header flashing is needed unless opening is protected by a covering.',
    category: 'exterior_install',
    triggerField: 'exteriorType',
    operator: 'equals',
    triggerValue: 'Siding',
    actionType: 'suggest_field',
    actionField: 'headerFlashing',
    actionValue: 'Suggested',
    severity: 'suggestion',
    priority: 5,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Labor Requirement Memos (Header Flashing)',
    sourcePage: '102',
    fieldRepGuidance: 'When exterior is siding, header flashing is commonly needed unless the opening is protected by a covering. Ask the rep to confirm.',
    installerNoteTemplate: 'Confirm whether header flashing is required. If under covering, may not be needed.',
    orderFormImpact: 'Order Form labor section - Header flashing note',
    contractImpact: 'Header flashing option selection',
    pricingImpact: 'Standard header flashing charge applies if selected',
    workbookMappingKey: 'Order Form Labor',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-wood-trim-exception',
    name: 'Wood Exterior → Trim Exception',
    description: 'Wood exterior is an exception for inside set trim requirement. Trim is not required.',
    category: 'exterior_install',
    triggerField: 'exteriorType',
    operator: 'equals',
    triggerValue: 'Wood',
    actionType: 'suggest_field',
    actionField: 'trim',
    actionValue: 'Not Required',
    severity: 'info',
    priority: 5,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Labor Requirement Memos (Trim)',
    sourcePage: '102',
    fieldRepGuidance: 'Trim is required when windows are inside set unless the exterior is wood.',
    installerNoteTemplate: 'Existing wood exterior - no vinyl trim required.',
    orderFormImpact: 'Order Form Labor Section',
    contractImpact: 'No trim charge',
    pricingImpact: 'No charge',
    workbookMappingKey: 'Order Form Labor',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-stucco-removal-review',
    name: 'Stucco → Cutback / Stucco Removal Review',
    description: 'Stucco exterior requires cutback/stucco removal review.',
    category: 'exterior_install',
    triggerField: 'exteriorType',
    operator: 'equals',
    triggerValue: 'Stucco',
    actionType: 'add_warning',
    actionField: 'stuccoRemoval',
    actionValue: 'Review',
    severity: 'warning',
    priority: 8,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Labor Requirement Memos',
    sourcePage: '103',
    fieldRepGuidance: 'Stucco removal or cutback may be needed. Review opening condition with photos.',
    installerNoteTemplate: 'Review stucco cutback requirements.',
    orderFormImpact: 'Installer instructions',
    contractImpact: 'Misc labor charge if stucco removal is added',
    pricingImpact: 'Misc labor charge',
    workbookMappingKey: 'Summary tab - Installer note',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-inside-set-trim-required',
    name: 'Inside Set → Trim Required',
    description: 'Trim is required for inside set windows unless exterior is wood.',
    category: 'exterior_install',
    triggerField: 'insideSet',
    operator: 'equals',
    triggerValue: 'true',
    actionType: 'require_field',
    actionField: 'trim',
    actionValue: 'Required',
    severity: 'blocker',
    priority: 15,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Labor Requirement Memos (Trim)',
    sourcePage: '102',
    fieldRepGuidance: 'Trim is required when windows are inside set unless the exterior is wood.',
    installerNoteTemplate: 'Inside set windows - vinyl trim required.',
    orderFormImpact: 'Order Form Labor - Trim checked',
    contractImpact: 'Trim line item added',
    pricingImpact: 'Standard trim pricing per opening',
    workbookMappingKey: 'Contract trim line',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-unknown-exterior-photo',
    name: 'Unknown Exterior → Photo Required',
    description: 'If exterior type is unknown, require photo upload and confirmation.',
    category: 'exterior_install',
    triggerField: 'exteriorType',
    operator: 'equals',
    triggerValue: 'Unknown',
    actionType: 'require_photo',
    actionField: 'photosAttached',
    actionValue: 'true',
    severity: 'warning',
    priority: 5,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Order Form Review',
    sourcePage: '101',
    fieldRepGuidance: 'Unknown exterior detected. Upload a photo and confirm the exterior surface with the customer.',
    installerNoteTemplate: 'Verify exterior surface on site before starting install.',
    orderFormImpact: 'Order Form notes',
    contractImpact: 'No direct pricing impact until verified',
    pricingImpact: 'Needs manual verification',
    workbookMappingKey: 'Photos & Measurements Tab',
    isActive: true,
    appliesToAllReps: true,
  },

  // ─── SCREENS ───
  {
    ruleKey: 'ww-picture-no-full-screen',
    name: 'Picture Window → No Full Screen',
    description: 'Picture windows cannot have a full screen.',
    category: 'product_defaults',
    triggerField: 'windowType',
    operator: 'equals',
    triggerValue: 'Picture',
    actionType: 'disable_option',
    actionField: 'screenType',
    actionValue: 'Full Screen',
    severity: 'blocker',
    priority: 10,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'L2000 Series Rules and Exceptions',
    sourcePage: '13',
    fieldRepGuidance: 'Picture windows cannot have full screens.',
    installerNoteTemplate: 'No screen for picture window.',
    orderFormImpact: 'Order Form - Screen column marked N/A',
    contractImpact: 'Screen option disabled',
    pricingImpact: 'No screen charge',
    workbookMappingKey: 'Order Form Screen Column',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-slider-3lite-no-full-screen',
    name: '3-Lite Slider → No Full Screen',
    description: '3-Lite Sliders cannot have a full screen.',
    category: 'product_defaults',
    triggerField: 'windowType',
    operator: 'equals',
    triggerValue: '3-Lite Slider',
    actionType: 'disable_option',
    actionField: 'screenType',
    actionValue: 'Full Screen',
    severity: 'blocker',
    priority: 10,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'L2000 Series Rules and Exceptions',
    sourcePage: '13',
    fieldRepGuidance: '3-Lite Slider windows cannot have full screens.',
    installerNoteTemplate: 'Standard half screens only.',
    orderFormImpact: 'Order Form - Screen column',
    contractImpact: 'Full screen disabled',
    pricingImpact: 'No full screen charge',
    workbookMappingKey: 'Order Form Screen Column',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-archtop-no-full-screen',
    name: 'Arch Top → No Full Screen',
    description: 'Arch-top/radius shape windows cannot have a full screen.',
    category: 'product_defaults',
    triggerField: 'specialShapeType',
    operator: 'equals',
    triggerValue: 'Arch / Radius',
    actionType: 'disable_option',
    actionField: 'screenType',
    actionValue: 'Full Screen',
    severity: 'blocker',
    priority: 10,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'L2000 Series Rules and Exceptions',
    sourcePage: '13',
    fieldRepGuidance: 'Arch top / radius windows cannot have full screens.',
    installerNoteTemplate: 'No full screens on special shape.',
    orderFormImpact: 'Order Form - Screen option',
    contractImpact: 'Option disabled',
    pricingImpact: 'No full screen charge',
    workbookMappingKey: 'Order Form Screen Column',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-ext-color-forces-full-screen',
    name: 'Exterior Color → Full Screen Required',
    description: 'Windows with exterior color must have full screens standard. Half screens are unavailable.',
    category: 'product_defaults',
    triggerField: 'exteriorColor',
    operator: 'is_not_empty',
    triggerValue: '',
    actionType: 'set_field',
    actionField: 'screenType',
    actionValue: 'Full Screen',
    severity: 'warning',
    priority: 10,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'L2000 Series Rules and Exceptions',
    sourcePage: '13',
    fieldRepGuidance: 'Full screens come standard with any window with an exterior color. Half screens are not available.',
    installerNoteTemplate: 'Full screen standard for colored units.',
    orderFormImpact: 'Order Form - Screen Column set to Full',
    contractImpact: 'Standard full screen applied',
    pricingImpact: 'Pricing included in color option',
    workbookMappingKey: 'Order Form Screen Column',
    isActive: true,
    appliesToAllReps: true,
  },

  // ─── COLORS ───
  {
    ruleKey: 'ww-l2000-no-ext-color',
    name: 'L2000/Fusion → No Exterior Color',
    description: 'L-2000 series cannot be ordered with exterior color.',
    category: 'color_validation',
    triggerField: 'series',
    operator: 'equals',
    triggerValue: 'L2000',
    actionType: 'disable_option',
    actionField: 'exteriorColor',
    actionValue: 'Color',
    severity: 'blocker',
    priority: 12,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'L2000 Series Rules and Exceptions',
    sourcePage: '13',
    fieldRepGuidance: 'No exterior color option is available on L-2000 series.',
    installerNoteTemplate: 'L2000 - White exterior only.',
    orderFormImpact: 'Blocker on order form generation',
    contractImpact: 'Exterior color disabled',
    pricingImpact: 'Blocked',
    workbookMappingKey: 'Validation blocker',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-l2000-no-int-color',
    name: 'L2000/Fusion → No Interior Color',
    description: 'L-2000 series cannot be ordered with interior color.',
    category: 'color_validation',
    triggerField: 'series',
    operator: 'equals',
    triggerValue: 'L2000',
    actionType: 'disable_option',
    actionField: 'interiorColor',
    actionValue: 'Color',
    severity: 'blocker',
    priority: 12,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'L2000 Series Rules and Exceptions',
    sourcePage: '13',
    fieldRepGuidance: 'No interior color option is available on L-2000 series.',
    installerNoteTemplate: 'L2000 - White interior only.',
    orderFormImpact: 'Blocker',
    contractImpact: 'Interior color disabled',
    pricingImpact: 'Blocked',
    workbookMappingKey: 'Validation blocker',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-03a0-no-int-color',
    name: '03A0 Single Hung → No Interior Color',
    description: '03A0 Single Hung windows do not support interior color options.',
    category: 'color_validation',
    triggerField: 'series',
    operator: 'equals',
    triggerValue: '03A0',
    actionType: 'disable_option',
    actionField: 'interiorColor',
    actionValue: 'Color',
    severity: 'blocker',
    priority: 12,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: '03A0 Series Pricing Rules and Exceptions',
    sourcePage: '15',
    fieldRepGuidance: 'Interior color is not available on 03A0 Single Hung windows.',
    installerNoteTemplate: '03A0 SH - White interior only.',
    orderFormImpact: 'Blocker',
    contractImpact: 'Disabled option',
    pricingImpact: 'Blocked',
    workbookMappingKey: 'Validation blocker',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-archtop-no-int-color',
    name: 'Arch Top S140/S144/S146 → No Interior Color',
    description: 'Interior color is not available on arch top windows S140, S144, S146.',
    category: 'color_validation',
    triggerField: 'productModel',
    operator: 'equals',
    triggerValue: 'S140', // Seeder represents first model; code filters S140/S144/S146
    actionType: 'disable_option',
    actionField: 'interiorColor',
    actionValue: 'Color',
    severity: 'blocker',
    priority: 12,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: '03A0 Series Pricing Rules and Exceptions',
    sourcePage: '15',
    fieldRepGuidance: 'Interior color is not available on arch-tops (S140, S144, S146).',
    installerNoteTemplate: 'Arch top - White interior only.',
    orderFormImpact: 'Blocker',
    contractImpact: 'Option disabled',
    pricingImpact: 'Blocked',
    workbookMappingKey: 'Validation blocker',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-clay-no-ext-color',
    name: 'Clay Vinyl + Exterior Color → Not Available',
    description: 'Clay vinyl interior cannot be paired with exterior painted colors.',
    category: 'color_validation',
    triggerField: 'vinylColor',
    operator: 'equals',
    triggerValue: 'Clay',
    actionType: 'disable_option',
    actionField: 'exteriorColor',
    actionValue: 'Color',
    severity: 'blocker',
    priority: 12,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Color Option Rules and Exceptions',
    sourcePage: '71',
    fieldRepGuidance: 'Exterior color is not available on clay vinyl windows.',
    installerNoteTemplate: 'Clay vinyl - exterior paint disabled.',
    orderFormImpact: 'Blocker',
    contractImpact: 'Exterior color disabled on clay',
    pricingImpact: 'Blocked',
    workbookMappingKey: 'Validation blocker',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-l2000-no-clay',
    name: 'L2000/Fusion + Clay → Not Available',
    description: 'L-2000 (Fusion) series does not support Clay vinyl color.',
    category: 'color_validation',
    triggerField: 'series',
    operator: 'equals',
    triggerValue: 'L2000',
    actionType: 'disable_option',
    actionField: 'vinylColor',
    actionValue: 'Clay',
    severity: 'blocker',
    priority: 12,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Color Option Rules and Exceptions',
    sourcePage: '71',
    fieldRepGuidance: 'Series CLAY cannot be made in L-2000 series (FUSION) & 0700 Series.',
    installerNoteTemplate: 'L2000 - Clay vinyl disabled.',
    orderFormImpact: 'Blocker',
    contractImpact: 'Clay vinyl option disabled',
    pricingImpact: 'Blocked',
    workbookMappingKey: 'Validation blocker',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-0700-no-clay',
    name: '0700 + Clay → Not Available',
    description: '0700 series does not support Clay vinyl color.',
    category: 'color_validation',
    triggerField: 'series',
    operator: 'equals',
    triggerValue: '0700',
    actionType: 'disable_option',
    actionField: 'vinylColor',
    actionValue: 'Clay',
    severity: 'blocker',
    priority: 12,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Color Option Rules and Exceptions',
    sourcePage: '71',
    fieldRepGuidance: 'Series CLAY cannot be made in 0700 Series.',
    installerNoteTemplate: '0700 - Clay vinyl disabled.',
    orderFormImpact: 'Blocker',
    contractImpact: 'Option disabled',
    pricingImpact: 'Blocked',
    workbookMappingKey: 'Validation blocker',
    isActive: true,
    appliesToAllReps: true,
  },

  // ─── GRIDS ───
  {
    ruleKey: 'ww-l2000-requires-b1-grid',
    name: 'L2000/Fusion → B1 Contoured Grid Required',
    description: 'L-2000 series requires B1 contoured grids if grids are selected.',
    category: 'grid_validation',
    triggerField: 'series',
    operator: 'equals',
    triggerValue: 'L2000',
    actionType: 'set_field',
    actionField: 'gridStyle',
    actionValue: 'B1 Colonial Contour Full',
    severity: 'blocker',
    priority: 15,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'L2000 Series Pricing Rules and Exceptions',
    sourcePage: '13',
    fieldRepGuidance: 'L-2000 series must have B1 CONTOURED grids.',
    installerNoteTemplate: 'L2000 - B1 contoured grids.',
    orderFormImpact: 'Order Form - Grid column set to B1',
    contractImpact: 'Contoured grids forced',
    pricingImpact: 'Standard contoured grid pricing applies',
    workbookMappingKey: 'Order Form Grid Style',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-ext-color-requires-b1-grid',
    name: 'Exterior Color → B1 Contoured Grid Required',
    description: 'Exterior color windows require B1 contoured grids if grids are selected.',
    category: 'grid_validation',
    triggerField: 'exteriorColor',
    operator: 'is_not_empty',
    triggerValue: '',
    actionType: 'set_field',
    actionField: 'gridStyle',
    actionValue: 'B1 Colonial Contour Full',
    severity: 'blocker',
    priority: 15,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Color Option Rules and Exceptions',
    sourcePage: '71',
    fieldRepGuidance: 'Windows with exterior color must have B1 CONTOURED grids. Half screens are not available.',
    installerNoteTemplate: 'Exterior color - contoured grids standard.',
    orderFormImpact: 'Grid column',
    contractImpact: 'Forced grid option',
    pricingImpact: 'Standard grid pricing',
    workbookMappingKey: 'Order Form Grid Style',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-diamond-forces-a1-flat',
    name: 'Diamond Grid → A1 Flat Required',
    description: 'Diamond grids must use A1 flat profile.',
    category: 'grid_validation',
    triggerField: 'gridStyle',
    operator: 'equals',
    triggerValue: 'D1 Diamond Full',
    actionType: 'set_field',
    actionField: 'gridStyle', // sets flat profile
    actionValue: 'A1 Colonial Flat Full',
    severity: 'blocker',
    priority: 15,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Color Option Rules and Exceptions',
    sourcePage: '71',
    fieldRepGuidance: 'Diamond grids must be A1 FLAT.',
    installerNoteTemplate: 'Diamond grids - Flat profile.',
    orderFormImpact: 'Grid Style column',
    contractImpact: 'Flat profile forced',
    pricingImpact: 'No adder beyond standard grid pricing',
    workbookMappingKey: 'Order Form Grid Style',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-sdl-requires-size',
    name: 'SDL Selected → Require SDL Size',
    description: 'SDL grids require size option 7/8 or 1-1/4 to be specified.',
    category: 'grid_validation',
    triggerField: 'sdlSelected',
    operator: 'equals',
    triggerValue: 'true',
    actionType: 'require_field',
    actionField: 'sdlSize',
    actionValue: '7/8',
    severity: 'blocker',
    priority: 15,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'SDL Window Grid Rules and Exceptions',
    sourcePage: '61',
    fieldRepGuidance: 'SDL grids come in a 7/8" or 1-1/4" option. This must be stated on the order form for all SDL grids to ensure correct pricing and ordering.',
    installerNoteTemplate: 'Verify SDL size before ordering.',
    orderFormImpact: 'Order Form - Grid column size specifier',
    contractImpact: 'SDL size specification',
    pricingImpact: 'Specific SDL grid pricing applies',
    workbookMappingKey: 'Order Form Grid Column',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-sdl-no-discount',
    name: 'SDL Selected → Non-Discountable / Audit Review',
    description: 'SDL grids cannot be discounted and require auditing review.',
    category: 'grid_validation',
    triggerField: 'sdlSelected',
    operator: 'equals',
    triggerValue: 'true',
    actionType: 'require_manager_review',
    actionField: 'workbookOrderFormMapped',
    actionValue: 'true',
    severity: 'blocker',
    priority: 20,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'SDL Window Grid Rules and Exceptions',
    sourcePage: '61',
    fieldRepGuidance: 'All SDL grids must state 7/8 inch or 1-1/4 inch on the order form and cannot be discounted. Require auditing manager signoff.',
    installerNoteTemplate: 'SDL grids - non-discountable.',
    orderFormImpact: 'SDL double-check paper stapled to folder',
    contractImpact: 'Full price grids line item',
    pricingImpact: 'SDL grids cannot be discounted',
    workbookMappingKey: 'Contract - Pricing lines',
    isActive: true,
    appliesToAllReps: true,
  },

  // ─── SPECIAL SHAPES ───
  {
    ruleKey: 'ww-special-shape-dims',
    name: 'Special Shape → Require Dimensions',
    description: 'Special shape windows require width, full height, and leg height measurements.',
    category: 'specialty_shape',
    triggerField: 'windowType',
    operator: 'equals',
    triggerValue: 'Special Shape',
    actionType: 'require_field',
    actionField: 'specialShapeUI',
    actionValue: 'Required',
    severity: 'blocker',
    priority: 15,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Special Shape Min-Max\'s',
    sourcePage: '33',
    fieldRepGuidance: 'Special shape requires width, full height, leg height, and UI as applicable.',
    installerNoteTemplate: 'Verify all measurements (width, full height, leg height) on sketch.',
    orderFormImpact: 'Diagram must show all three measurement points',
    contractImpact: 'Measurement fields required',
    pricingImpact: 'No direct impact (validation blocker)',
    workbookMappingKey: 'Photos & Measurements Tab',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-special-shape-radius-trim',
    name: 'Special Shape Radius → Special Shape Trim Required',
    description: 'Radius/arch special shapes require special shape trim.',
    category: 'specialty_shape',
    triggerField: 'specialShapeType',
    operator: 'equals',
    triggerValue: 'Arch / Radius',
    actionType: 'require_field',
    actionField: 'trim',
    actionValue: 'Required',
    severity: 'blocker',
    priority: 15,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Special Shape Pricing Rules and Exceptions',
    sourcePage: '60',
    fieldRepGuidance: 'Special shape trim is required on radius/arch shapes unless integrated nail fins apply.',
    installerNoteTemplate: 'Radius shape - Special shape bent vinyl trim required.',
    orderFormImpact: 'Trim labor section',
    contractImpact: 'Special shape trim line item',
    pricingImpact: 'Special shape trim charge ($150+ standard)',
    workbookMappingKey: 'Contract specialty line',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-special-shape-polygon-trim',
    name: 'Special Shape Polygon → No Bent Trim Required',
    description: 'Polygon special shapes do not require special shape bent trim.',
    category: 'specialty_shape',
    triggerField: 'specialShapeType',
    operator: 'equals',
    triggerValue: 'Polygon',
    actionType: 'set_field',
    actionField: 'trim',
    actionValue: 'Not Required',
    severity: 'info',
    priority: 10,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Special Shape Pricing Rules and Exceptions',
    sourcePage: '60',
    fieldRepGuidance: 'We will no longer require special shape trim to be charged on polygon shapes as they do not have a bent trim piece.',
    installerNoteTemplate: 'Polygon shape - Standard miter trim (no bent trim).',
    orderFormImpact: 'Trim labor section',
    contractImpact: 'No specialty trim charge',
    pricingImpact: 'Zero trim adder',
    workbookMappingKey: 'Contract specialty line',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-special-shape-max-ui-adder',
    name: 'Special Shape over max UI → $150 Adder',
    description: 'If a special shape exceeds the maximum book UI, charge the full price of max UI + $150 adder.',
    category: 'specialty_shape',
    triggerField: 'windowType',
    operator: 'equals',
    triggerValue: 'Special Shape',
    actionType: 'add_price',
    actionField: 'specialShapeAdder',
    actionValue: '150',
    severity: 'warning',
    priority: 15,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Special Shape Pricing Rules and Exceptions',
    sourcePage: '60',
    fieldRepGuidance: 'Special shape over max UI but within min/max: charge max UI full price + $150 adder. Non-discountable.',
    installerNoteTemplate: 'Oversize special shape - check weight.',
    orderFormImpact: 'Pricing column',
    contractImpact: '$150 adder line item',
    pricingImpact: '$150 surcharge, non-discountable',
    workbookMappingKey: 'Summary tab - Pricing surcharge',
    isActive: true,
    appliesToAllReps: true,
  },

  // ─── ORIEL ───
  {
    ruleKey: 'ww-oriel-dh-max-50',
    name: '3000 DH Oriel Max 50 Inches',
    description: '3000 series Double Hung oriel windows have a maximum height limit of 50 inches.',
    category: 'oriel',
    triggerField: 'series',
    operator: 'equals',
    triggerValue: '3000',
    actionType: 'block_final',
    actionField: 'orielHeight',
    actionValue: '50',
    severity: 'blocker',
    priority: 15,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: '3000 Model Rules and Exceptions',
    sourcePage: '17',
    fieldRepGuidance: '3000 DH oriel windows can be max 50 inches. Oriel over 50 inches requires 03A0 Single Hung.',
    installerNoteTemplate: 'Verify oriel split limit.',
    orderFormImpact: 'Blocker',
    contractImpact: 'Forced model change to Single Hung if > 50"',
    pricingImpact: 'Blocked',
    workbookMappingKey: 'Validation blocker',
    isActive: true,
    appliesToAllReps: true,
  },

  // ─── MULLS ───
  {
    ruleKey: 'ww-mull-casement-pair-0972',
    name: 'Mull Casement Pair → 0972 Double Casement Required',
    description: 'A mulled pair of 0971 casements within double-casement limits must be ordered as a single 0972.',
    category: 'mull_joined',
    triggerField: 'mullSelected',
    operator: 'equals',
    triggerValue: 'true',
    actionType: 'suggest_field',
    actionField: 'productModel',
    actionValue: '0972',
    severity: 'warning',
    priority: 10,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Casement Series Pricing Rules and Exceptions',
    sourcePage: '30',
    fieldRepGuidance: 'Mull Casement Pair (0971) within limits: order/sell as 0972 double casement to save cost.',
    installerNoteTemplate: 'Install as double casement 0972 unit.',
    orderFormImpact: 'Order Form - model set to 0972',
    contractImpact: 'Line item changed to 0972',
    pricingImpact: 'Priced as 0972 instead of two 0971s',
    workbookMappingKey: 'Order Form Model Column',
    isActive: true,
    appliesToAllReps: true,
  },

  // ─── TEMPERING ───
  {
    ruleKey: 'ww-tempered-adjacent-door',
    name: 'Tempered Adjacent Door',
    description: 'Windows adjacent to doors (within 24") with bottom edge < 60" from floor require tempered safety glass.',
    category: 'tempered_glass',
    triggerField: 'adjacentToDoor',
    operator: 'equals',
    triggerValue: 'true',
    actionType: 'require_field',
    actionField: 'temperedRequired',
    actionValue: 'true',
    severity: 'blocker',
    priority: 20,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Tempering Guidelines',
    sourcePage: '115',
    fieldRepGuidance: 'Adjacent to door + bottom edge under 60 inches + within 24 inches → tempered required.',
    installerNoteTemplate: 'Safety glass adjacent to door - tempered logo must be visible.',
    orderFormImpact: 'Order Form - Glass option set to Tempered',
    contractImpact: 'Tempered glass surcharge added',
    pricingImpact: 'Tempering pricing calculated separately',
    workbookMappingKey: 'Order Form Glass Option',
    isActive: true,
    appliesToAllReps: true,
  },

  // ─── LABOR ───
  {
    ruleKey: 'ww-clear-story-labor',
    name: 'Clear Story Labor Charge Required',
    description: 'Clear story windows require $225 for the first unit and $75 for each additional unit.',
    category: 'pricing',
    triggerField: 'clearStory',
    operator: 'equals',
    triggerValue: 'true',
    actionType: 'add_price',
    actionField: 'clearStoryLineItem',
    actionValue: '225',
    severity: 'warning',
    priority: 15,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Labor Requirement Memos (Clear Story)',
    sourcePage: '103',
    fieldRepGuidance: 'Clear story windows: first window = $225 minimum, additional = $75 each.',
    installerNoteTemplate: 'Clear story - bring extension ladders.',
    orderFormImpact: 'Labor section clear story units counted',
    contractImpact: 'Clear story surcharge line item',
    pricingImpact: 'Labor surcharge added per formula',
    workbookMappingKey: 'Summary tab - Labor pricing',
    isActive: true,
    appliesToAllReps: true,
  },
  {
    ruleKey: 'ww-tapcon-concrete-charge',
    name: 'Tapcon Required → $10 Charge',
    description: 'Concrete attachments require tapcons charged at $10 per unit.',
    category: 'pricing',
    triggerField: 'tapconRequired',
    operator: 'equals',
    triggerValue: 'true',
    actionType: 'add_price',
    actionField: 'tapconLineItem',
    actionValue: '10',
    severity: 'warning',
    priority: 10,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'L2000 Series Rules and Exceptions',
    sourcePage: '13',
    fieldRepGuidance: 'Tapcons required for concrete installation: charge $10 per unit.',
    installerNoteTemplate: 'Use concrete tapcons for anchors.',
    orderFormImpact: 'Labor options checklist',
    contractImpact: 'Tapcon surcharge line',
    pricingImpact: '$10 per window unit',
    workbookMappingKey: 'Summary tab - Surcharges',
    isActive: true,
    appliesToAllReps: true,
  },

  // ─── AC SASH ───
  {
    ruleKey: 'ww-ac-sash-charge',
    name: 'AC Sash Selected → $90 Charge & Notes',
    description: 'AC sashes cost $90, pay 0% commission, and require AC unit measurements and installer notes.',
    category: 'pricing',
    triggerField: 'acSash',
    operator: 'equals',
    triggerValue: 'true',
    actionType: 'add_price',
    actionField: 'ACsashLineItem',
    actionValue: '90',
    severity: 'warning',
    priority: 15,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'AC Sash Memos',
    sourcePage: '104',
    fieldRepGuidance: 'AC sash selected: $90 line item, 0% commission. Require AC unit measurements and installer note: "Please bring AC SASH for install".',
    installerNoteTemplate: 'Please bring AC SASH for install.',
    orderFormImpact: 'Order Form notes with AC unit dimensions',
    contractImpact: 'AC Sash option line item',
    pricingImpact: '$90 flat charge',
    workbookMappingKey: 'Summary tab - Surcharges',
    isActive: true,
    appliesToAllReps: true,
  },

  // ─── FINANCE ───
  {
    ruleKey: 'ww-wells-fargo-device-restriction',
    name: 'Wells Fargo Device Restriction',
    description: 'Wells Fargo financing remote authorization must be completed on the customer device, not the salesperson\'s device.',
    category: 'final_export',
    triggerField: 'financeProvider',
    operator: 'equals',
    triggerValue: 'Wells Fargo',
    actionType: 'add_warning',
    actionField: 'customerDeviceFinance',
    actionValue: 'false',
    severity: 'blocker',
    priority: 20,
    sourceDocument: '2026 BTR Pricing Guidelines',
    sourceSection: 'Audit Wells Fargo Memos',
    sourcePage: '120',
    fieldRepGuidance: 'Wells Fargo customer must complete remote authorization on customer\'s own device. Do not let salesperson complete Wells Fargo remote application on salesperson\'s device.',
    installerNoteTemplate: 'Customer device remote auth required.',
    orderFormImpact: 'Blocker on order finalization',
    contractImpact: 'Verification warning',
    pricingImpact: 'None',
    workbookMappingKey: 'Validation blocker',
    isActive: true,
    appliesToAllReps: true,
  },
];

async function main() {
  console.log(`🚀 Smart Rules Import script running... Dry run mode: ${DRY_RUN}`);

  let added = 0;
  let updated = 0;
  let skipped = 0;

  for (const r of SEED_RULES) {
    // Check if exists
    const existing = await prisma.businessRule.findUnique({
      where: { ruleKey: r.ruleKey },
    });

    if (existing) {
      // Idempotently update
      if (DRY_RUN) {
        console.log(`[DRY RUN] Would UPDATE rule: ${r.ruleKey} - "${r.name}"`);
        updated++;
      } else {
        await prisma.businessRule.update({
          where: { ruleKey: r.ruleKey },
          data: {
            name: r.name,
            description: r.description,
            category: r.category,
            triggerField: r.triggerField,
            operator: r.operator,
            triggerValue: r.triggerValue,
            actionType: r.actionType,
            actionField: r.actionField,
            actionValue: r.actionValue,
            severity: r.severity,
            priority: r.priority,
            sourceDocument: r.sourceDocument,
            sourceSection: r.sourceSection,
            sourcePage: r.sourcePage,
            fieldRepGuidance: r.fieldRepGuidance,
            installerNoteTemplate: r.installerNoteTemplate,
            orderFormImpact: r.orderFormImpact,
            contractImpact: r.contractImpact,
            pricingImpact: r.pricingImpact,
            workbookMappingKey: r.workbookMappingKey,
            appliesToAllReps: r.appliesToAllReps,
          },
        });
        console.log(`✅ UPDATED rule: ${r.ruleKey}`);
        updated++;
      }
    } else {
      // Create new
      if (DRY_RUN) {
        console.log(`[DRY RUN] Would ADD new rule: ${r.ruleKey} - "${r.name}"`);
        added++;
      } else {
        const payload = {
          ruleKey: r.ruleKey,
          name: r.name,
          description: r.description,
          category: r.category,
          triggerField: r.triggerField,
          operator: r.operator,
          triggerValue: r.triggerValue,
          actionType: r.actionType,
          actionField: r.actionField,
          actionValue: r.actionValue,
          message: r.fieldRepGuidance,
          severity: r.severity,
          priority: r.priority,
          sourceDocument: r.sourceDocument,
          sourceSection: r.sourceSection,
          sourcePage: r.sourcePage,
          fieldRepGuidance: r.fieldRepGuidance,
          installerNoteTemplate: r.installerNoteTemplate,
          orderFormImpact: r.orderFormImpact,
          contractImpact: r.contractImpact,
          pricingImpact: r.pricingImpact,
          workbookMappingKey: r.workbookMappingKey,
          appliesToAllReps: r.appliesToAllReps,
        };
        await prisma.businessRule.create({
          data: payload,
        });
        console.log(`➕ ADDED rule: ${r.ruleKey}`);
        added++;
      }
    }
  }

  console.log(`\n📊 SEED REPORT:`);
  console.log(`  Added:   ${added}`);
  console.log(`  Updated: ${updated}`);
  console.log(`  Skipped: ${skipped}`);
  console.log(`  Total:   ${SEED_RULES.length}`);
}

main()
  .catch((e) => {
    console.error('❌ Error during import:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
