// Quick test: Generate a commission report from template
const ExcelJS = require('exceljs');
const path = require('path');
const fs = require('fs');

const TEMPLATE = path.resolve(__dirname, '../templates/Commission_Sheet_BTR_Template.xlsx');
const OUTPUT = path.resolve(__dirname, '../test_commission_report.xlsx');

async function test() {
  console.log('=== Commission Report Generation Test ===\n');

  // 1. Verify template exists
  if (!fs.existsSync(TEMPLATE)) {
    console.error('❌ Template not found:', TEMPLATE);
    process.exit(1);
  }
  console.log('✅ Template found:', TEMPLATE);

  // 2. Load template
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.readFile(TEMPLATE);
  const ws = wb.getWorksheet('Commission');
  console.log('✅ Workbook loaded — Sheet: Commission');

  // 3. Count formulas before
  let formulasBefore = 0;
  let mergesBefore = Object.keys(ws._merges || {}).length;
  for (let r = 1; r <= ws.rowCount; r++) {
    const row = ws.getRow(r);
    for (let c = 1; c <= 26; c++) {
      const cell = row.getCell(c);
      if (cell.value && typeof cell.value === 'object' && (cell.value.formula || cell.value.sharedFormula)) {
        formulasBefore++;
      }
    }
  }
  console.log(`✅ Formulas before: ${formulasBefore}`);
  console.log(`✅ Merges before: ${mergesBefore}`);

  // 4. Write test input data (customer info only)
  const FORMULA_CELLS = ['I14','I16','I17','I18','I19','I20','I21','I22','I23','I25','I27',
    'I30','I31','I32','I33','I34','I35','I36','I37','I39','I40','I41','I42','I43',
    'V11','V12','V13','V14','V15','V16','V17','V18','V19','V20','V21','V23','V24',
    'V26','V28','V29','V30','V31','V32','V33','V35','V36','V37','V39','V40','V41','V42',
    'T45','U45','V45','T46','C25','D25','C27','D27',
    'AA18','AA19','AA26','AA27','AB18','AB19','AB26','AB27','AD26','AD27'];

  const writeCell = (addr, value) => {
    if (FORMULA_CELLS.includes(addr)) return;
    ws.getCell(addr).value = value;
  };

  // Customer info
  writeCell('D4', 'CUST-12345');
  writeCell('J4', '(225) 555-1234');
  writeCell('S4', new Date('2025-06-15'));
  writeCell('D5', 'John Smith');
  writeCell('N5', '42');
  writeCell('S5', 'Ned Pearson');
  writeCell('D6', '123 Main St');
  writeCell('O6', 'Sold');
  writeCell('D7', 'Baton Rouge, LA 70801');
  writeCell('S7', 8);
  writeCell('D8', 'BTR');
  writeCell('S8', 4500);

  // Products
  writeCell('A13', 5);  // 5x DH Mech — should calc $100
  writeCell('A17', 2);  // 2x Picture — should calc $40
  writeCell('A18', 1);  // 1x 2 Lite Slider — should calc $20

  // Options
  writeCell('L12', 3);  // 3x Beige/Clay — should calc $15
  writeCell('L18', 8);  // 8x Colonial Grids — should calc $40

  writeCell('M47', 'Test report generated by commission engine');

  console.log('✅ Input data written to cells');

  // 5. Count formulas after
  let formulasAfter = 0;
  let mergesAfter = Object.keys(ws._merges || {}).length;
  for (let r = 1; r <= ws.rowCount; r++) {
    const row = ws.getRow(r);
    for (let c = 1; c <= 26; c++) {
      const cell = row.getCell(c);
      if (cell.value && typeof cell.value === 'object' && (cell.value.formula || cell.value.sharedFormula)) {
        formulasAfter++;
      }
    }
  }
  console.log(`✅ Formulas after: ${formulasAfter} (${formulasAfter === formulasBefore ? 'PRESERVED ✓' : '⚠️ CHANGED'})`);
  console.log(`✅ Merges after: ${mergesAfter} (${mergesAfter === mergesBefore ? 'PRESERVED ✓' : '⚠️ CHANGED'})`);

  // 6. Verify page setup preserved
  console.log(`✅ Print area: ${ws.pageSetup.printArea}`);
  console.log(`✅ Orientation: ${ws.pageSetup.orientation}`);
  console.log(`✅ Scale: ${ws.pageSetup.scale}%`);
  console.log(`✅ Fit to page: ${ws.pageSetup.fitToPage}`);

  // 7. Verify specific formulas
  const t45 = ws.getCell('T45');
  console.log(`✅ T45 formula: ${t45.value?.formula || t45.value?.sharedFormula || 'NO FORMULA ⚠️'}`);

  // 8. Save output
  await wb.xlsx.writeFile(OUTPUT);
  const stats = fs.statSync(OUTPUT);
  console.log(`\n✅ Generated report: ${OUTPUT}`);
  console.log(`   Size: ${(stats.size / 1024).toFixed(1)} KB`);

  // 9. Verify output is valid by re-reading it
  const wb2 = new ExcelJS.Workbook();
  await wb2.xlsx.readFile(OUTPUT);
  const ws2 = wb2.getWorksheet('Commission');
  console.log(`✅ Output workbook re-read — ${ws2.rowCount} rows`);

  // Verify customer name written correctly
  const name = ws2.getCell('D5').value;
  console.log(`✅ Customer name (D5): "${name}" ${name === 'John Smith' ? '✓' : '⚠️'}`);

  // Verify formula preserved
  const t45_2 = ws2.getCell('T45');
  const hasFormula = t45_2.value && typeof t45_2.value === 'object' && t45_2.value.formula;
  console.log(`✅ T45 formula preserved: ${hasFormula ? '✓' : '⚠️'} ${hasFormula ? t45_2.value.formula : ''}`);

  // Cleanup
  fs.unlinkSync(OUTPUT);
  console.log('✅ Test file cleaned up');
  console.log('\n=== ALL TESTS PASSED ===');
}

test().catch(e => { console.error('❌ Test failed:', e); process.exit(1); });
